function all_images = retrieve_uiuc(number_of_images_per_class, number_of_classes)
% function all_images = retrieve_uiuc(number_of_images_per_class, number_of_classes)
%
% retrieves images from the UIUC Texture databases
% available at http://www-cvr.ai.uiuc.edu/ponce_grp/data/
%
% inputs :
% - number_of_images_per_class : [optional] <1x1 int> between 1 and 40
% - number_of_classes : [optional] <1x1 int> between 1 and 25
%
% output :
% - all_images : <nested cell> of images
%   - all_images{i}{j} : <480x640 double> the j-th image of the j-th classe
%
% NOTE :
% this function requires you to add a global variable to matlab
% To do so, add the following two lines to your startup.m
%   global mpath
%   mpath = '/path/to/uiuc/database/on/your/system';

startup;
if ~exist('number_of_images_per_class', 'var')
  number_of_images_per_class = 40;
end
if ~exist('number_of_classes', 'var')
  number_of_classes = 25;
end

path_for_classes = {
  'T01_bark1',...
  'T02_bark2',...
  'T03_bark3',...
  'T04_wood1',...
  'T05_wood2',...
  'T06_wood3',...
  'T07_water',...
  'T08_granite',...
  'T09_marble',...
  'T10_floor1',...
  'T11_floor2',...
  'T12_pebbles',...
  'T13_wall',...
  'T14_brick1',...
  'T15_brick2',...
  'T16_glass1',...
  'T17_glass2',...
  'T18_carpet1',...
  'T19_carpet2',...
  'T20_upholstery',...
  'T21_wallpaper',...
  'T22_fur',...
  'T23_knit',...
  'T24_corduroy',...
  'T25_plaid',...
  };

if ~exist('mpath','var')
  fprintf(['WARNING : This function requires you to add a global variable to matlab \n',...
    'To do so, add the following two lines to your startup.m \n',...
    ' global mpath  \n',...
    ' mpath = ''/path/to/uiuc/database/on/your/system'' \n' ]);
end

for i=1:number_of_classes
  for j=1:number_of_images_per_class
    filename=fullfile(mpath,'cvr_uiuc',path_for_classes{i},['T',formatnumb(i),'_',formatnumb(j),'.jpg']);
    all_images{i}{j}=imreadBW(filename);
  end
end
end

function str=formatnumb(x)
if (x<10)
  str=['0',int2str(x)];
else
  str=int2str(x);
end
end